"button 1":
  title: Default
  subtitle: Botão padrão básico do projeto. Aplicado nas tags <code>a</code> <code>button</code> e <code>input</code>.
  sourceCode: button-default.html.twig

"button 2":
  title: Cores
  subtitle: Variações de cores do botão.
  sourceCode: button-colors.html.twig

"button 3":
  title: Redes sociais
  subtitle: Botões de compartilhamento que usam apenas o link sem scripts externos
  sourceCode: button-social.html.twig

"button 4":
  title: Redes sociais sem texto
  sourceCode: button-social-simple.html.twig

"button 5":
  title: Redes sociais menor
  sourceCode: button-social-small.html.twig

"button 6":
  title: Redes sociais sem texto menor
  sourceCode: button-social-simple-small.html.twig
