"Tabs":
  title: Tabs
  link: "/navegacao/#tabs"
  id: "tabs"
  subtitle: Todos os Headings HTML.
  sourceCode: tabs.html.twig
"Accordion":
  title: Accordion
  link: "/navegacao/#accordion"
  id: "accordion"
  subtitle: Todos os Headings HTML.
  sourceCode: accordion.html.twig
